services:
  - type: web
    name: evasu-fullstack
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: famcoorsinan@evasu.org
      - key: ADMIN_PASSWORD
        value: familycoordinatersinan
